kind: pipeline
name: spigot_ci

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: default
    image: ubuntu:20.04
    environment:
      BOT_TOKEN:
        from_secret: bot_token
      CHAT_ID:
        from_secret: chat_id
    commands:
      - ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - apt-get update && apt-get install -y openjdk-8-jdk git curl wget
      - chmod +x start.sh
      - bash start.sh
